name: Run Python Script on Push

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Change Directory
      run: cd GithubAlertCiCd  # Change to your repository directory

    - name: Run Python Script
      run: |
        python my_script.py
